name: Code Engine function test 
description: Github action to test IBM Cloud Code Engine functions
author: Skywalker_etw

branding:
  icon: cloud
  color: blue

inputs:

  runtime:
    description: "Programming Language used by your Function"
    required: true

  source-dir:
    description: "Path to the directory containing the source code"
    required: false
    default: .

  test-file:
    description: ""
    required: false

runs:
  using: composite

  steps:

  - name: Set test file
    id: test-file
    shell: bash
    run: |
      if [[ "${{ inputs.test-file }}" != "" ]] ; then
          echo "test-file=${{ inputs.test-file }}" >> "$GITHUB_OUTPUT"
      else
        case ${{ echo "${{ inputs.runtime }}" | cut -d'-' -f1 }} in

        python)
          echo "file=*test*.py" >> "$GITHUB_OUTPUT"
          ;;

        nodejs)
          echo "file=*test*.js" >> "$GITHUB_OUTPUT"
          ;;

        esac
      fi

  - name: Install Python
    uses: actions/setup-python@v4
    if: inputs.runtime ==  echo "${{ inputs.runtime }}" | cut -d'-' -f1
    with:
      python-version: echo "${{ inputs.runtime }}" | cut -d'-' -f2 
  
  - name: Test Python Function
    shell: bash
    if: inputs.runtime == 'python'
    working-directory: inputs.runtime
    run: |
        if [ -e "requirements.txt" ]; then
          virtualenv virtualenv
          source virtualenv/bin/activate
          pip install -r requirements.txt"
        fi
        mv __main__.py main__.py
        python ${{ steps.test-file.outputs.file }} -v
        
  - name: Install Nodejs
    uses: actions/setup-node@v3
    if: inputs.runtime == echo "${{ inputs.runtime }}" | cut -d'-' -f1
    with:
      node-version: echo "${{ inputs.runtime }}" | cut -d'-' -f2

  - name: Test Nodejs Function
    shell: bash
    working-directory: inputs.runtime
    if: inputs.runtime == echo "${{ inputs.runtime }}" | cut -d'-' -f1
    run: |
      if [ -e "package.json" ]; then
        npm install
      fi
      npm install mocha chai
      npx mocha ${{ steps.test-file.outputs.file }}