name: Test Code Engine Function

on:
  push:
    branches:
      - master

jobs:

  test-py-function:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run test
      uses: ./.github/actions/fn-test
      with:
        runtime: python-3.11
        source-dir: py-fn-testing

  test-js-function:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3  

    - name: Run test
      uses: ./.github/actions/fn-test
      with:
        runtime: nodejs-18
        source-dir: js-fn-testing